# Generated by Django 2.1.7 on 2019-03-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='employee',
        ),
    ]
